!TEST.mac
/out,OUT_FCdata,txt
fclist,2
/output

AAA= $ *DIM,AAA,ARRAY,1,9
!*SREAD, StrArray, Fname, Ext, --, nChar, nSkip, nRead
!*VREAD,ParR    ,Fname       ,Ext, --,Label, n1, n2, n3, NSKIP
*VREAD ,AAA(1,1), OUT_FCdata,txt,   ,JIK  ,  9, 1,  1, 5
(E11.3,E10.3,E10.3,E10.3,E10.3,E10.3,E10.3,E10.3,E10.3)
!0.120E+11-0.100E+11 0.100E+11-0.100E+11 0.100E+11-0.800E+02 0.709E+02 0.100E+11 0.346E+02 -1.00 -1.00 -1.00